/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "6b56ef714768608375710f5b0d5f7a9519cdf265"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
