#!/usr/bin/env python
# Copyright 2017 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import base64
import hashlib
from optparse import OptionParser
import os
import sys

def computeIntegrity(input_path):
  hasher = hashlib.sha256()
  with open(input_path, 'r') as f:
    hasher.update(f.read())
  return base64.b64encode(hasher.digest())

def writeHeader(input_path, integrity, output_path):
  with open(output_path, 'w') as f:
    input_filename = os.path.split(input_path)[1]
    f.write('// DO NOT MODIFY THIS FILE DIRECTLY!\n')
    f.write('// IT IS GENERATED BY generate_integrity_header.py\n')
    f.write('// FROM ' + input_filename + '\n')

    f.write('\n')

    define_name = input_filename.upper().replace('-', '_').replace('.', '_')
    define_name = define_name + '_INTEGRITY'

    f.write('#define ' + define_name + ' "' + integrity + '"\n')

    f.write('\n')

def main():
  parser = OptionParser(usage=__doc__)
  (_, args) = parser.parse_args()

  if len(args) != 2:
    print('Please specify path to input and output file as positional '
          'parameters.')
    parser.print_help()
    return 1

  input_path = args[0]
  output_path = args[1]

  integrity = computeIntegrity(input_path)
  writeHeader(input_path, integrity, output_path)

  return 0

if __name__ == '__main__':
  sys.exit(main())
