// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef CHROME_BROWSER_NOTIFICATIONS_NOTIFICATION_OPERATION_H_
#define CHROME_BROWSER_NOTIFICATIONS_NOTIFICATION_OPERATION_H_

enum NotificationOperation {
  NOTIFICATION_OPERATION_CLICK = 0,
  NOTIFICATION_OPERATION_CLOSE = 1,
  NOTIFICATION_OPERATION_DISABLE_PERMISSION = 2,
  NOTIFICATION_OPERATION_SETTINGS = 3,
  NOTIFICATION_OPERATION_MAX = NOTIFICATION_OPERATION_SETTINGS
};

#endif  // CHROME_BROWSER_NOTIFICATIONS_NOTIFICATION_OPERATION_H_
