#!/usr/bin/env python

import base64
import glob
import json
import os
import urllib2


os.chdir(os.path.dirname(__file__))


TRYBOTS_PY_URL = 'https://chromium.googlesource.com/chromium/tools/build/+/master/scripts/slave/recipe_modules/chromium_tests/trybots.py?format=TEXT'

def freeze(x):
  return x

try:
  trybots_py_text = base64.b64decode(urllib2.urlopen(TRYBOTS_PY_URL).read())
  trybots_py_text = trybots_py_text.replace('from recipe_engine.types import freeze', '')
  exec trybots_py_text
except Exception as e:
  print 'Exception while fetching %s: %s' % (TRYBOTS_PY_URL, str(e))


matched_trybots = {}
for mastername, builders in TRYBOTS.items():
  matched_trybots.setdefault(mastername, set())
  for builder, vals in builders['builders'].items():
    for bot_id in vals['bot_ids']:
      matched_mastername = bot_id['mastername']
      matched_trybots.setdefault(matched_mastername, set())
      matched_trybots[matched_mastername].add(bot_id['buildername'])
      if 'tester' in bot_id:
        matched_trybots[matched_mastername].add(bot_id['tester'])


filenames = glob.glob('*.json')
if 'trybot_analyze_config.json' in filenames:
  filenames.remove('trybot_analyze_config.json')

# This master is access-protected.
if 'chromium.angle.json' in filenames:
  filenames.remove('chromium.angle.json')

missing_json_entries = {}
extra_json_entries = {}

for filename in filenames:
  testing_json = json.load(open(filename))

  mastername = filename.replace('.json', '')
  try:
    CBE = 'https://chrome-build-extract.appspot.com/get_master/'
    buildbot_json = json.load(urllib2.urlopen(CBE + mastername))
  except Exception as e:
    print 'Exception while fetching %s: %s' % (mastername, str(e))
    continue

  testing_builders = set(testing_json.keys())
  testing_builders -= set([
      'AAAAA1 AUTOGENERATED FILE DO NOT EDIT',
      'AAAAA2 See generate_buildbot_json.py to make changes',
      'AAAAA2 See //tools/perf/generate_perf_data to make changes',
  ])

  buildbot_builders = set(buildbot_json['builders'].keys())
  buildbot_builders.update(matched_trybots.get(mastername, set()))

  only_testing = testing_builders - buildbot_builders
  only_buildbot = buildbot_builders - testing_builders

  if only_testing:
    extra_json_entries[filename] = sorted(only_testing)
  if only_buildbot:
    missing_json_entries[filename] = sorted(only_buildbot)

def print_var(name, val):
  print "%s = {" % name
  masternames = sorted(val.keys())
  for mastername in masternames:
    print '  "%s": {' % mastername
    buildernames = val[mastername]
    for buildername in buildernames:
      print '    "%s": {}%s' % (buildername, ',' if buildername != buildernames[-1] else '')
    print '  }%s' % (',' if mastername != masternames[-1] else '')
  print '}'

if extra_json_entries:
  print_var('extra_json_entries', extra_json_entries)

if missing_json_entries:
  print_var('missing_json_entries', missing_json_entries)
