# Copyright (c) 2017 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Create function which clear some device policies
from ChromeDeviceSettingsProto for DeviceOffHours policy.
"""

import sys
from optparse import OptionParser


def main():
  parser = OptionParser(usage=__doc__)
  (opts, args) = parser.parse_args()
  off_hours_cleaner_path = args[0]
  sys.path.insert(0, args[1])
  sys.path.insert(0, args[2])
  sys.path.insert(0, args[3])
  from chrome_device_policy_pb2 import ChromeDeviceSettingsProto
  file = open(off_hours_cleaner_path, 'w')
  settings = ChromeDeviceSettingsProto()
  file.write('//\n')
  file.write('// DO NOT MODIFY THIS FILE DIRECTLY!\n')
  file.write('// IT IS GENERATED BY generate_device_policy_remover.py\n')
  file.write('// FROM chrome_device_policy_pb2.py\n')
  file.write('//\n\n')
  file.write('#include "chrome/browser/chromeos/policy/' \
             'device_policy_remover.h"\n\n')
  file.write('namespace policy {\n\n')
  file.write('namespace em = enterprise_management;\n\n')
  file.write('em::ChromeDeviceSettingsProto ClearPolicies(\n')
  file.write('    const em::ChromeDeviceSettingsProto& input_policies,\n')
  file.write('    const std::set<std::string>& policies_to_clear) {\n')
  file.write('  em::ChromeDeviceSettingsProto policies;\n')
  file.write('  policies.CopyFrom(input_policies);\n')
  for group in settings.DESCRIPTOR.fields:
    file.write('  if (policies_to_clear.find("' + group.name + '") != ')
    file.write('policies_to_clear.end()) {\n')
    file.write('    policies.clear_' + group.name + '();\n')
    file.write('  }\n')
  file.write('  return policies;\n')
  file.write('}\n')
  file.write('}\n')
  file.close()
  return 0

if __name__ == '__main__':
  sys.exit(main())
