# Copyright 2017 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Create function which removes the specified device policies
from ChromeDeviceSettingsProto.
This function is primarily intended to be used
for the implementation of the DeviceOffHours policy.
"""

import sys
from optparse import OptionParser


def main():
  parser = OptionParser(usage=__doc__)
  (opts, args) = parser.parse_args()
  off_hours_cleaner_path = args[0]
  sys.path.insert(0, args[1])
  sys.path.insert(0, args[2])
  sys.path.insert(0, args[3])
  from chrome_device_policy_pb2 import ChromeDeviceSettingsProto
  with open(off_hours_cleaner_path, 'wt') as file:
    settings = ChromeDeviceSettingsProto()
    file.write('//\n'
               '// DO NOT MODIFY THIS FILE DIRECTLY!\n'
               '// IT IS GENERATED BY generate_device_policy_remover.py\n'
               '// FROM chrome_device_policy_pb2.py\n'
               '//\n\n'
               '#include "chrome/browser/chromeos/policy/'
               'device_policy_remover.h"\n\n'
               'namespace policy {\n\n'
               'namespace em = enterprise_management;\n\n'
               'void RemovePolicies(\n'
               '    em::ChromeDeviceSettingsProto* policies,\n'
               '    std::vector<std::string>* policies_to_remove) {\n'
               '  std::sort(policies_to_remove->begin(),'
               ' policies_to_remove->end());\n')
    for field in settings.DESCRIPTOR.fields:
      file.write('  if (std::binary_search(policies_to_remove->begin(),\n'
                 '      policies_to_remove->end(), "{name}"))\n'
                 '    policies->clear_{name}();\n'.format(name=field.name))
    file.write('}\n}\n')
  return 0

if __name__ == '__main__':
  sys.exit(main())
