// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "ash/system/power/power_button_display_controller.h"

#include "ash/accessibility/accessibility_controller.h"
#include "ash/media_controller.h"
#include "ash/public/cpp/ash_switches.h"
#include "ash/shell.h"
#include "ash/system/power/scoped_display_forced_off.h"
#include "ash/touch/touch_devices_controller.h"
#include "ash/wm/tablet_mode/tablet_mode_controller.h"
#include "base/command_line.h"
#include "base/time/tick_clock.h"
#include "chromeos/dbus/dbus_thread_manager.h"
#include "ui/events/devices/input_device_manager.h"
#include "ui/events/devices/stylus_state.h"
#include "ui/events/event.h"

namespace ash {

namespace {

// Returns true if device is currently in tablet/tablet mode, otherwise false.
bool IsTabletModeActive() {
  TabletModeController* tablet_mode_controller =
      Shell::Get()->tablet_mode_controller();
  return tablet_mode_controller &&
         tablet_mode_controller->IsTabletModeWindowManagerEnabled();
}

}  // namespace

PowerButtonDisplayController::PowerButtonDisplayController(
    base::TickClock* tick_clock)
    : tick_clock_(tick_clock),
      display_forced_off_observer_(this),
      weak_ptr_factory_(this) {
  chromeos::DBusThreadManager::Get()->GetPowerManagerClient()->AddObserver(
      this);
  ui::InputDeviceManager::GetInstance()->AddObserver(this);
  Shell::Get()->PrependPreTargetHandler(this);

  display_forced_off_observer_.Add(Shell::Get()->display_forced_off_setter());

  disable_touchscreen_while_screen_off_ =
      !base::CommandLine::ForCurrentProcess()->HasSwitch(
          switches::kTouchscreenUsableWhileScreenOff);

  if (Shell::Get()->display_forced_off_setter()->backlights_forced_off_set())
    UpdateTouchscreenStatus();
}

PowerButtonDisplayController::~PowerButtonDisplayController() {
  Shell::Get()->RemovePreTargetHandler(this);
  ui::InputDeviceManager::GetInstance()->RemoveObserver(this);
  chromeos::DBusThreadManager::Get()->GetPowerManagerClient()->RemoveObserver(
      this);
}

bool PowerButtonDisplayController::IsScreenOn() const {
  return screen_state_ == ScreenState::ON;
}

void PowerButtonDisplayController::SetDisplayForcedOff(bool forced_off) {
  if ((display_forced_off_ && display_forced_off_->IsActive()) == forced_off)
    return;

  if (forced_off) {
    display_forced_off_ =
        Shell::Get()->display_forced_off_setter()->ForceDisplayOff();
  } else {
    display_forced_off_.reset();
  }

  if (forced_off)
    Shell::Get()->media_controller()->SuspendMediaSessions();

  // Send an a11y alert.
  Shell::Get()->accessibility_controller()->TriggerAccessibilityAlert(
      forced_off ? mojom::AccessibilityAlert::SCREEN_OFF
                 : mojom::AccessibilityAlert::SCREEN_ON);
}

void PowerButtonDisplayController::BrightnessChanged(int level,
                                                     bool user_initiated) {
  const ScreenState old_state = screen_state_;
  if (level != 0)
    screen_state_ = ScreenState::ON;
  else
    screen_state_ = user_initiated ? ScreenState::OFF : ScreenState::OFF_AUTO;

  if (screen_state_ != old_state)
    screen_state_last_changed_ = tick_clock_->NowTicks();

  // Disable the touchscreen when the screen is turned off due to inactivity:
  // https://crbug.com/743291
  if ((screen_state_ == ScreenState::OFF_AUTO) !=
          (old_state == ScreenState::OFF_AUTO) &&
      disable_touchscreen_while_screen_off_) {
    UpdateTouchscreenStatus();
  }
}

void PowerButtonDisplayController::OnBacklightsForcedOffChanged() {
  UpdateTouchscreenStatus();
}

void PowerButtonDisplayController::SuspendDone(
    const base::TimeDelta& sleep_duration) {
  // Stop forcing backlights off on resume to handle situations where the power
  // button resumed but we didn't receive the event (crbug.com/735291).
  SetDisplayForcedOff(false);
}

void PowerButtonDisplayController::LidEventReceived(
    chromeos::PowerManagerClient::LidState state,
    const base::TimeTicks& timestamp) {
  SetDisplayForcedOff(false);
}

void PowerButtonDisplayController::OnKeyEvent(ui::KeyEvent* event) {
  // Ignore key events generated by the power button since power button activity
  // is already handled elsewhere.
  if (event->key_code() == ui::VKEY_POWER)
    return;

  if (!IsTabletModeActive())
    SetDisplayForcedOff(false);
}

void PowerButtonDisplayController::OnMouseEvent(ui::MouseEvent* event) {
  if (event->flags() & ui::EF_IS_SYNTHESIZED)
    return;

  if (!IsTabletModeActive())
    SetDisplayForcedOff(false);
}

void PowerButtonDisplayController::OnStylusStateChanged(ui::StylusState state) {
  if (state == ui::StylusState::REMOVED)
    SetDisplayForcedOff(false);
}

void PowerButtonDisplayController::UpdateTouchscreenStatus() {
  DisplayForcedOffSetter* forced_off_setter =
      Shell::Get()->display_forced_off_setter();
  const bool disable_touchscreen = forced_off_setter->backlights_forced_off() ||
                                   (screen_state_ == ScreenState::OFF_AUTO &&
                                    disable_touchscreen_while_screen_off_);
  Shell::Get()->touch_devices_controller()->SetTouchscreenEnabled(
      !disable_touchscreen, TouchscreenEnabledSource::GLOBAL);
}
}  // namespace ash
