// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef COMPONENTS_NETWORK_CHANGE_MANAGER_CLIENT_NETWORK_CHANGE_MANAGER_CLIENT_EXPORT_H_
#define COMPONENTS_NETWORK_CHANGE_MANAGER_CLIENT_NETWORK_CHANGE_MANAGER_CLIENT_EXPORT_H_

#if defined(COMPONENT_BUILD)
#if defined(WIN32)

#if defined(NETWORK_CHANGE_MANAGER_CLIENT_IMPLEMENTATION)
#define NETWORK_CHANGE_MANAGER_CLIENT_EXPORT __declspec(dllexport)
#else
#define NETWORK_CHANGE_MANAGER_CLIENT_EXPORT __declspec(dllimport)
#endif  // defined(NETWORK_CHANGE_MANAGER_CLIENT_IMPLEMENTATION)

#else  // defined(WIN32)
#if defined(NETWORK_CHANGE_MANAGER_CLIENT_IMPLEMENTATION)
#define NETWORK_CHANGE_MANAGER_CLIENT_EXPORT \
  __attribute__((visibility("default")))
#else
#define NETWORK_CHANGE_MANAGER_CLIENT_EXPORT
#endif  // defined(NETWORK_CHANGE_MANAGER_CLIENT_IMPLEMENTATION)
#endif

#else  // defined(COMPONENT_BUILD)
#define NETWORK_CHANGE_MANAGER_CLIENT_EXPORT
#endif

#endif  // COMPONENTS_NETWORK_CHANGE_MANAGER_CLIENT_NETWORK_CHANGE_MANAGER_CLIENT_EXPORT_H_
