// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "components/feedback/feedback_util_chromeos.h"

#include <string>

#include "base/logging.h"
#include "third_party/cros_system_api/dbus/debugd/dbus-constants.h"

namespace feedback_util {

namespace {

constexpr char kIwlwifiDumpDisplayValue[] =
    "<Four files generated by Intel Wi-Fi firmware: csr.lst, fh_regs.lst, "
    "radio_reg.lst, monitor.lst.sysmon.  The first three are binary files "
    "containing register dumps, and are asserted by Intel to contain no "
    "personal or device-identifying information.  The last file is an "
    "execution trace from the Intel firmware; it has been scrubbed of any "
    "personal or device-identifying information, but is too large to display "
    "here.  These files were generated in response to recent Wi-Fi problems "
    "with your device, and will be shared with Intel to help troubleshoot "
    "these problems.>";

}  // namespace

bool GetDisplayValue(const std::string& key, std::string* to_display) {
  DCHECK(to_display);
  if (key == debugd::kIwlwifiDumpKey) {
    *to_display = kIwlwifiDumpDisplayValue;
    return true;
  }

  return false;
}

}  // namespace feedback_util
