# Copyright (c) 2017 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
import sys
from optparse import OptionParser

# env PYTHONPATH=:out_veyron_minnie/Release/pyproto:third_party/protobuf/python:out_veyron_minnie/Release/pyproto/chrome/browser/chromeos/policy/proto python components/policy/tools/off_hours_generator.py chrome/browser/chromeos/policy/device_off_hours_cleaner.cc
# Example of generated code
# #include "chrome/browser/chromeos/policy/device_off_hours_controller.h"
# namespace em = enterprise_management;
#
# em::ChromeDeviceSettingsProto clear_policies(
#     em::ChromeDeviceSettingsProto* input_policies,
#         std::set<std::string> off_policies) {
#   em::ChromeDeviceSettingsProto policies;
#   policies.CopyFrom(*input_policies);
#   if (off_policies.find("allow_new_users")) {
#     policies.clear_allow_new_users();
#   }
#   ...
#   return policices;
# }
def main():
  parser = OptionParser(usage=__doc__)
  (opts, args) = parser.parse_args()
  off_hours_cleaner_path = args[0]
  sys.path.insert(0, args[1])
  sys.path.insert(0, args[2])
  sys.path.insert(0, args[3])
  from chrome_device_policy_pb2 import ChromeDeviceSettingsProto
  file = open(off_hours_cleaner_path, 'w')
  settings = ChromeDeviceSettingsProto()
  file.write('//\n')
  file.write('// DO NOT MODIFY THIS FILE DIRECTLY!\n')
  file.write('// IT IS GENERATED BY generate_off_hours_cleaner.py\n')
  file.write('// FROM chrome_device_policy_pb2.py\n')
  file.write('//\n\n')
  file.write('#include "chrome/browser/chromeos/policy/' \
             'device_off_hours_controller.h"\n\n')
  file.write('namespace policy {\n\n')
  file.write('namespace em = enterprise_management;\n\n')
  file.write('em::ChromeDeviceSettingsProto DeviceOffHoursController::' \
             'ClearPolicies(\n')
  file.write('    em::ChromeDeviceSettingsProto* input_policies,\n')
  file.write('    std::set<std::string> off_policies) {\n')
  file.write('  em::ChromeDeviceSettingsProto policies;\n')
  file.write('  policies.CopyFrom(*input_policies);\n')
  for group in settings.DESCRIPTOR.fields:
    # group_message = eval('dp.' + group.message_type.name + '()')
    file.write('  if (off_policies.find("' + group.name + '") !=\n')
    file.write('      off_policies.end()) {\n')
    file.write('    policies.clear_' + group.name + '();\n')
    file.write('  }\n')
  file.write('  return policies;\n')
  file.write('}\n')
  file.write('}\n')
  file.close()
  return 0

if __name__ == '__main__':
  sys.exit(main())

