// Copyright 2018 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Use the <code>chrome.safeBrowsingPrivate</code> API to observe events.
namespace safeBrowsingPrivate {

  dictionary PolicySpecifiedPasswordReuse {
    // URL where this reuse happened.
    DOMString url;

    // The user name of the policy specified password.
    DOMString userName;

    // If this a phishing url.
    boolean isPhishing;
  };

  interface Events {
    // Fired when Chrome detects a reuse of a policy specified password.
    //
    // |url|: URL where this reuse happened.
    // |userName|: The user name of the policy specified password.
    // |isPhishing|: If this a phishing url.
    static void onPolicySpecifiedPasswordReuseDetected(
        PolicySpecifiedPasswordReuse dict);

    // Fired when the user changed their policy specified password.
    //
    // |userName|: The user name of the policy specified password.
    static void onPolicySpecifiedPasswordChanged(DOMString userName);
  };

};
