// Introduced in DOM Level 3:
interface DOMConfiguration {
  void               setParameter(in DOMString name, 
                                  in DOMUserData value)
                                        raises(DOMException);
  DOMUserData        getParameter(in DOMString name)
                                        raises(DOMException);
  boolean            canSetParameter(in DOMString name, 
                                     in DOMUserData value);
  readonly attribute DOMStringList   parameterNames;
};
