// Introduced in DOM Level 3:
interface DOMError {

  // ErrorSeverity
  const unsigned short      SEVERITY_WARNING               = 1;
  const unsigned short      SEVERITY_ERROR                 = 2;
  const unsigned short      SEVERITY_FATAL_ERROR           = 3;

  readonly attribute unsigned short  severity;
  readonly attribute DOMString       message;
  readonly attribute DOMString       type;
  readonly attribute DOMObject       relatedException;
  readonly attribute DOMObject       relatedData;
  readonly attribute DOMLocator      location;
};
