// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "net/test/embedded_test_server/embedded_test_server.h"

namespace web {
namespace test {

// This method sets up an EmbeddedTestServer instance, registers passed-in
// handlers to the server.  The method registers the default public file
// directory "ios/testing/data/http_server_files/" to the server. It also
// accepts input file directories.
void RegisterHandlerAndStart(
    const net::EmbeddedTestServer::HandleRequestCallback& handler,
    const char* sourceDirectory = NULL);

// This method releases the EmbeddedTestServer instance.
void ShutDownServer();

// This method returns the URL generated by EmbeddedTestServer.
GURL GetURL(const std::string& relative_url);

}  // namespace test
}  // namespace web
